- name: USing filters
  hosts: centos
  vars:
   URL: https://archive.apache.org/dist/tomcat/tomcat-8/v8.5.54/bin/apache-tomcat-8.5.54.tar.gz
  tasks:
   - debug:
       msg: filename is is {{URL.split("/") | last}}