##- name: Tomcat download and unarchive
#  get_url:
 #  url: "{{TOMCAT_URL}}"
#   dest: /home/{{APP_USER}}
#  become_user: "{{APP_USER}}"

- name: install existing tomcat
  package:
    name: tomcat
    state: present


- name: download application and place in webapps folder
  get_url:
    url: "{{WEBAPP_URL}}"
    dest: "{{TOMCAT_LOCATION}}/webapps"

- name: Download sql jar
  get_url:
    url: "{{SQLJAR_URL}}"
    dest: "{{TOMCAT_LOCATION}}/lib"

- name: Configure the db connection 
  template:
   src: context.xml.j2
   dest: "/etc/tomcat/context.xml"


- name: Restart tomcat service
  service:
   name: tomcat
   state: restarted
   enabled: yes

  



   
