- name: Download tomcat from url
  hosts: all
  tasks:
    - name: using get_url
      get_url:
        url: https://archive.apache.org/dist/tomcat/tomcat-8/v8.5.54/bin/apache-tomcat-8.5.54.tar.gz
        dest: /home/student
      become: yes
